Load the data.

In [42]:
import pandas as pd
url='https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_0e922a809bfe468b8552ddbd1e7753b2.csv'
df=pd.read_csv(url,header=None)
df.head()

0       1       2     3     4       5       6          7        8   \
0  winter  small_  medium  8.00   9.8  60.800   6.238  578.00000  105.000   
1  spring  small_  medium  8.35   8.0  57.750   1.288  370.00000  428.750   
2  autumn  small_  medium  8.10  11.4  40.020   5.330  346.66699  125.667   
3  spring  small_  medium  8.07   4.8  77.364   2.302   98.18200   61.182   
4  autumn  small_  medium  8.06   9.0  55.350  10.416  233.70000   58.222   

          9     10   11    12    13   14    15   16   17  
0  170.00000  50.0  0.0   0.0   0.0  0.0  34.2  8.3  0.0  
1  558.75000   1.3  1.4   7.6   4.8  1.9   6.7  0.0  2.1  
2  187.05701  15.6  3.3  53.6   1.9  0.0   0.0  0.0  9.7  
3  138.70000   1.4  3.1  41.0  18.9  0.0   1.4  0.0  1.4  
4   97.58000  10.5  9.2   2.9   7.5  0.0   7.5  4.1  1.0

In [43]:
df.shape

(200, 18)

The original dataset was very messy. Columns 3 to 10 did not only contain missing values that were marked with "XXXXXXX", but also contained entries that looked like "2.822008777.59961". To make it worse, columns 3 to 10 in the original dataset were of data type "object". So, the "mean()" method did not work on these columns. My original plan with columns 3 to 10 was that I was going to replace the cells with "XXXXXXX" with 0.0, then convert these columns into float, so that I could calcualte the means of these columns and replace the 0.0 with the mean of the corresponding column. However, as I applied the "dataframe.astype(float)" to these columns, it kept returning the same error message that Python could not covert string to float. Further probe revealed that these coulmns did not only contain "XXXXXXX", but also entries that looked like "2.822008777.59961". There were quite a few of them scatter around in columns 3 to 8. Finding them one by one would take a long time.

On the other hand, MS Excel could recognize columns as numbers and calcualte the mean of each column, automatically skipping the cells with "XXXXXXX" and entries that are like "2.822008777.59961". I could nest the "ISNUMBER" function inside the "IF" function and easily take care of all those problematic cells. The "ISNUMBER" function tests whether a cell is a number. If it is, then keep that number; if it is not (i.e, XXXXXXX or 2.822008777.59961), the replace it with with the mean of the column. Very fast and convenient.

For the reasons above, I have cleaned the dataset before loading it here.

Verify that there is no empty cells.

In [44]:
df.isna().any()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
dtype: bool

In [45]:
from sklearn.preprocessing import LabelEncoder
df_object=df.iloc[:,0:3]
df_object=df_object.apply(LabelEncoder().fit_transform)
df_object.head()

0  1  2
0  3  2  2
1  1  2  2
2  0  2  2
3  1  2  2
4  0  2  2

In [46]:
df_s=df.iloc[:,3:18]
df=pd.concat([df_object,df_s],axis=1)
df

0   1   2     3     4           5          6           7           8   \
0     3   2   2  8.00   9.8   60.800000   6.238000  578.000000  105.000000   
1     1   2   2  8.35   8.0   57.750000   1.288000  370.000000  428.750000   
2     0   2   2  8.10  11.4   40.020000   5.330000  346.666990  125.667000   
3     1   2   2  8.07   4.8   77.364000   2.302000   98.182000   61.182000   
4     0   2   2  8.06   9.0   55.350000  10.416000  233.700000   58.222000   
..   ..  ..  ..   ...   ...         ...        ...         ...         ...   
195   0   0   2  8.40   8.4   17.375000   3.833000   83.750000   53.625000   
196   1   0   2  8.30  10.6   14.320000   3.200000  125.333000   35.333000   
197   0   0   2  8.20   7.0  139.989000   2.978000   60.110000   78.333000   
198   3   0   2  8.00   7.6   43.636279   3.011558  154.447197   83.325566   
199   2   0   2  8.50   6.7   82.852000   2.800000   27.069000   64.000000   

             9          10    11    12    13   14    15    16   17  
0    170.000000  50.000000   0.0   0.0   0.0  0.0  34.2   8.3  0.0  
1    558.750000   1.300000   1.4   7.6   4.8  1.9   6.7   0.0  2.1  
2    187.057010  15.600000   3.3  53.6   1.9  0.0   0.0   0.0  9.7  
3    138.700000   1.400000   3.1  41.0  18.9  0.0   1.4   0.0  1.4  
4     97.580000  10.500000   9.2   2.9   7.5  0.0   7.5   4.1  1.0  
..          ...        ...   ...   ...   ...  ...   ...   ...  ...  
195   79.750000   2.338000  12.7  21.7   5.6  0.0   1.0   0.0  0.0  
196   75.904000   4.667000  18.0   7.0   1.7  0.0   4.8  10.3  1.0  
197  140.220000  31.738000   0.0  15.9   2.4  1.0   0.0   0.0  0.0  
198  111.550601  13.540729   0.0  12.5   3.7  1.0   0.0   0.0  4.9  
199  140.517000  18.300000   2.4  10.5   9.0  7.8   0.0   0.0  5.8  

[200 rows x 18 columns]

Standardize the dataset.

In [47]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
df=pd.DataFrame(scaler.fit_transform(df))
df

0         1        2         3         4             5  \
0    1.212446  1.159382  1.09984 -0.019710  0.287463  3.770155e-01   
1   -0.577142  1.159382  1.09984  0.568222 -0.470990  3.100197e-01   
2   -1.471936  1.159382  1.09984  0.148270  0.961644 -7.943460e-02   
3   -0.577142  1.159382  1.09984  0.097876 -1.819352  7.408577e-01   
4   -1.471936  1.159382  1.09984  0.081078 -0.049627  2.573017e-01   
..        ...       ...      ...       ...       ...           ...   
195 -1.471936 -1.505864  1.09984  0.652213 -0.302445 -5.768510e-01   
196 -0.577142 -1.505864  1.09984  0.484232  0.624554 -6.439566e-01   
197 -1.471936 -1.505864  1.09984  0.316251 -0.892353  2.116468e+00   
198  1.212446 -1.505864  1.09984 -0.019710 -0.639535 -4.393168e-11   
199  0.317652 -1.505864  1.09984  0.820193 -1.018762  8.614062e-01   

                6             7             8             9            10  \
0    1.499615e+00  2.370772e+00  1.870033e-01  5.761715e-01  1.843970e+00   
1   -8.010907e-01  1.206524e+00  2.980263e+00  4.408318e+00 -6.190889e-01   
2    1.077586e+00  1.075921e+00  3.653146e-01  7.443129e-01  1.041500e-01   
3   -3.297947e-01 -3.149358e-01 -1.910509e-01  2.676283e-01 -6.140313e-01   
4    3.441503e+00  4.436054e-01 -2.165893e-01 -1.377168e-01 -1.537884e-01   
..            ...           ...           ...           ...           ...   
195  3.817972e-01 -3.957167e-01 -2.562514e-01 -3.134780e-01 -5.665909e-01   
196  8.758575e-02 -1.629623e-01 -4.140716e-01 -3.513904e-01 -4.487990e-01   
197 -1.559739e-02 -5.280380e-01 -4.307500e-02  2.826118e-01  9.203479e-01   
198 -2.091550e-11 -1.063496e-10  3.796239e-11  3.647317e-10 -1.618436e-10   
199 -9.832983e-02 -7.129799e-01 -1.667377e-01  2.855395e-01  2.407056e-01   

           11        12        13        14        15        16        17  
0   -0.791883 -0.643226 -0.632861 -0.471679  2.907351  0.326073 -0.495313  
1   -0.726139  0.061730  0.009434  0.003880  0.108886 -0.546820 -0.080248  
2   -0.636915  4.328569 -0.378619 -0.471679 -0.572922 -0.546820  1.421892  
3   -0.646307  3.159826  1.896175 -0.471679 -0.430455 -0.546820 -0.218603  
4   -0.359853 -0.374230  0.370725 -0.471679  0.190296 -0.115632 -0.297663  
..        ...       ...       ...       ...       ...       ...       ...  
195 -0.195494  1.369609  0.116483 -0.471679 -0.471160 -0.546820 -0.495313  
196  0.053393  0.006076 -0.405382 -0.471679 -0.084463  0.536409 -0.297663  
197 -0.791883  0.831616 -0.311714 -0.221385 -0.572922 -0.546820 -0.495313  
198 -0.791883  0.516241 -0.137759 -0.221385 -0.572922 -0.546820  0.473172  
199 -0.679179  0.330726  0.571442  1.480615 -0.572922 -0.546820  0.651057  

[200 rows x 18 columns]

This dataset is from the COIL 1999 challenge. I found it on UCI's KDD Archive. According to the descriptions of the dataset on the website, columns 0 to 10 are predictor variables that predictor variables that represent the seaon, river size and chemical concentration. Columns 11 to 17 are target variables that represent the algae population distribution.

Separate the predictor variables and target variables. The task is a multi-output regression.

In [48]:
X=df.iloc[:,0:11]
X

0         1        2         3         4             5  \
0    1.212446  1.159382  1.09984 -0.019710  0.287463  3.770155e-01   
1   -0.577142  1.159382  1.09984  0.568222 -0.470990  3.100197e-01   
2   -1.471936  1.159382  1.09984  0.148270  0.961644 -7.943460e-02   
3   -0.577142  1.159382  1.09984  0.097876 -1.819352  7.408577e-01   
4   -1.471936  1.159382  1.09984  0.081078 -0.049627  2.573017e-01   
..        ...       ...      ...       ...       ...           ...   
195 -1.471936 -1.505864  1.09984  0.652213 -0.302445 -5.768510e-01   
196 -0.577142 -1.505864  1.09984  0.484232  0.624554 -6.439566e-01   
197 -1.471936 -1.505864  1.09984  0.316251 -0.892353  2.116468e+00   
198  1.212446 -1.505864  1.09984 -0.019710 -0.639535 -4.393168e-11   
199  0.317652 -1.505864  1.09984  0.820193 -1.018762  8.614062e-01   

                6             7             8             9            10  
0    1.499615e+00  2.370772e+00  1.870033e-01  5.761715e-01  1.843970e+00  
1   -8.010907e-01  1.206524e+00  2.980263e+00  4.408318e+00 -6.190889e-01  
2    1.077586e+00  1.075921e+00  3.653146e-01  7.443129e-01  1.041500e-01  
3   -3.297947e-01 -3.149358e-01 -1.910509e-01  2.676283e-01 -6.140313e-01  
4    3.441503e+00  4.436054e-01 -2.165893e-01 -1.377168e-01 -1.537884e-01  
..            ...           ...           ...           ...           ...  
195  3.817972e-01 -3.957167e-01 -2.562514e-01 -3.134780e-01 -5.665909e-01  
196  8.758575e-02 -1.629623e-01 -4.140716e-01 -3.513904e-01 -4.487990e-01  
197 -1.559739e-02 -5.280380e-01 -4.307500e-02  2.826118e-01  9.203479e-01  
198 -2.091550e-11 -1.063496e-10  3.796239e-11  3.647317e-10 -1.618436e-10  
199 -9.832983e-02 -7.129799e-01 -1.667377e-01  2.855395e-01  2.407056e-01  

[200 rows x 11 columns]

In [49]:
y=df.iloc[:,11:18]
y

11        12        13        14        15        16        17
0   -0.791883 -0.643226 -0.632861 -0.471679  2.907351  0.326073 -0.495313
1   -0.726139  0.061730  0.009434  0.003880  0.108886 -0.546820 -0.080248
2   -0.636915  4.328569 -0.378619 -0.471679 -0.572922 -0.546820  1.421892
3   -0.646307  3.159826  1.896175 -0.471679 -0.430455 -0.546820 -0.218603
4   -0.359853 -0.374230  0.370725 -0.471679  0.190296 -0.115632 -0.297663
..        ...       ...       ...       ...       ...       ...       ...
195 -0.195494  1.369609  0.116483 -0.471679 -0.471160 -0.546820 -0.495313
196  0.053393  0.006076 -0.405382 -0.471679 -0.084463  0.536409 -0.297663
197 -0.791883  0.831616 -0.311714 -0.221385 -0.572922 -0.546820 -0.495313
198 -0.791883  0.516241 -0.137759 -0.221385 -0.572922 -0.546820  0.473172
199 -0.679179  0.330726  0.571442  1.480615 -0.572922 -0.546820  0.651057

[200 rows x 7 columns]

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFECV
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
import numpy as np

estimator=RandomForestRegressor(n_estimators=100,criterion="mse",random_state=0)
features=RFECV(estimator,step=1,cv=KFold(8),scoring="neg_mean_squared_error")
features.fit(X,y)

print("Optimal number of features : %d" % features.n_features_)

Optimal number of features : 11


In [10]:
from sklearn.feature_selection import RFE
import numpy as np
selector = RFE(estimator, n_features_to_select=features.n_features_, step=1)
selector = selector.fit(X,y)
selector=pd.DataFrame(selector.ranking_).rename(columns={0:"Importance"})
selector

Importance
0            1
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1
10           1

In [11]:
features=selector[selector["Importance"]==1]
X=X.iloc[:,features.index]
X.head()

0         1        2         3         4         5         6   \
0  1.212446  1.159382  1.09984 -0.019710  0.287463  0.377016  1.499615   
1 -0.577142  1.159382  1.09984  0.568222 -0.470990  0.310020 -0.801091   
2 -1.471936  1.159382  1.09984  0.148270  0.961644 -0.079435  1.077586   
3 -0.577142  1.159382  1.09984  0.097876 -1.819352  0.740858 -0.329795   
4 -1.471936  1.159382  1.09984  0.081078 -0.049627  0.257302  3.441503   

         7         8         9         10  
0  2.370772  0.187003  0.576172  1.843970  
1  1.206524  2.980263  4.408318 -0.619089  
2  1.075921  0.365315  0.744313  0.104150  
3 -0.314936 -0.191051  0.267628 -0.614031  
4  0.443605 -0.216589 -0.137717 -0.153788

In [12]:
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 1000, num = 10)]
max_features = ['auto', 'sqrt','log2']
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 8,10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [13]:
from sklearn.model_selection import RandomizedSearchCV
tree = RandomForestRegressor(criterion="mse",random_state=0)
rf_random = RandomizedSearchCV(estimator =tree, param_distributions = random_grid, n_iter = 200, cv = 7, verbose=2, n_jobs = -1)

In [14]:
rf_random.fit(X,y)

Fitting 7 folds for each of 200 candidates, totalling 1400 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   33.7s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed:  5.0min
[Parallel(n_jobs=-1)]: Done 644 tasks      | elapsed:  9.0min
[Parallel(n_jobs=-1)]: Done 1009 tasks      | elapsed: 15.1min
[Parallel(n_jobs=-1)]: Done 1400 out of 1400 | elapsed: 21.8min finished


RandomizedSearchCV(cv=7, estimator=RandomForestRegressor(random_state=0),
                   n_iter=200, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 8, 10],
                                        'n_estimators': [200, 288, 377, 466,
                                                         555, 644, 733, 822,
                                                         911, 1000]},
                   verbose=2)

In [15]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 10,
 'min_samples_leaf': 4,
 'max_features': 'sqrt',
 'max_depth': 70,
 'bootstrap': True}

In [51]:
best_random = rf_random.best_estimator_
y_pred=best_random.predict(X)
y_pred=pd.DataFrame(y_pred)
y_pred

0         1         2         3         4         5         6
0   -0.554241  0.155767 -0.270080 -0.095698  0.651938  0.722251 -0.079170
1   -0.473707  0.202635  0.353658  0.192508  0.039901 -0.112132  0.041265
2   -0.549971  1.509970 -0.259076 -0.271534  0.036199  0.232046  0.183391
3   -0.497467  0.491198  0.884692  0.099067 -0.126679 -0.285311  0.021391
4   -0.440279  0.107607 -0.183844 -0.199843  0.428200  0.579430 -0.150764
..        ...       ...       ...       ...       ...       ...       ...
195 -0.383055  0.524783  0.035254 -0.175510  0.014624  0.085024 -0.004380
196 -0.316793 -0.019273 -0.236276 -0.225188  0.236539  0.487073 -0.125510
197 -0.602247  0.505983  0.464697 -0.018215 -0.209481 -0.271250 -0.017037
198 -0.460738  0.205766  0.180843  0.043792 -0.189689 -0.173290  0.048300
199 -0.444001  0.199433  0.381469  0.245637 -0.118798 -0.309502  0.070380

[200 rows x 7 columns]

In [52]:
from sklearn.metrics import mean_squared_error as mse
n_classes=y.shape[1]
for i in range(n_classes):
    print("The root means squared error for the ",i,"th target is ,", np.sqrt(mse(y.iloc[:,i],y_pred.iloc[:,i]))  )  

The root means squared error for the  0 th target is , 0.5767856943173066
The root means squared error for the  1 th target is , 0.6898990499585558
The root means squared error for the  2 th target is , 0.784477338415592
The root means squared error for the  3 th target is , 0.8228185831726548
The root means squared error for the  4 th target is , 0.7514195903591024
The root means squared error for the  5 th target is , 0.7274923271681885
The root means squared error for the  6 th target is , 0.7551043063084052


In [53]:
from sklearn.metrics import r2_score as r2
for i in range(n_classes):
    print("The R-squared for the ",i,"th target is ,", r2(y.iloc[:,i],y_pred.iloc[:,i]))

The R-squared for the  0 th target is , 0.6673182628309026
The R-squared for the  1 th target is , 0.524039300866282
The R-squared for the  2 th target is , 0.38459530551238885
The R-squared for the  3 th target is , 0.322969579185745
The R-squared for the  4 th target is , 0.4353685992245587
The R-squared for the  5 th target is , 0.47075491391141333
The R-squared for the  6 th target is , 0.42981748659450214


Load the test data.

In [19]:
url_t='https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_fe6dd697d4b74c3f88fda9626f9c435c.csv'
df_t=pd.read_csv(url_t,header=None)
df_t

0       1       2     3     4        5      6          7          8   \
0    summer  small_  medium  7.95   5.7  57.3330  2.460  273.33301  295.66699   
1    winter  small_  medium  7.98   8.8  59.3330  7.392  286.66699   33.33300   
2    summer  small_  medium  8.00   7.2  80.0000  1.957  174.28600   47.85700   
3    spring  small_  high__  8.35   8.4  68.0000  3.026  458.00000   45.20000   
4    spring  small_  medium  8.10  13.2  19.0000  0.000  130.00000    6.00000   
..      ...     ...     ...   ...   ...      ...    ...        ...        ...   
135  summer  medium  high__  8.12  10.2   7.6130  0.699   33.56000   28.03400   
136  winter  large_  low___  8.43  10.8  35.6420  6.225  134.00000  103.50000   
137  winter  large_  low___  8.70  11.7  21.4656  3.765   91.45000   38.00000   
138  summer  large_  low___  8.10   8.2  26.5400  2.805   42.75000   48.50000   
139  autumn  large_  low___  8.35  11.1  22.5600  3.140   76.20000   41.00000   

            9          10    11    12   13   14    15    16    17  
0    380.00000  10.912868   1.2  36.5  1.9  0.0   1.2   0.0  28.0  
1    138.00000   7.100000   1.2   0.0  0.0  0.0  23.2  46.4   0.0  
2    113.71400   4.500000   7.0  23.0  6.5  1.4  21.2   0.0   2.1  
3    111.80000   3.200000   1.4  38.2  2.4  0.0   4.8   1.0   1.2  
4     40.00000   2.000000   3.9  55.4  8.4  0.0   0.0   0.0   0.0  
..         ...        ...   ...   ...  ...  ...   ...   ...   ...  
135   49.65800   2.200000  18.1   1.7  2.0  0.0   1.7   5.9   0.0  
136  108.80637  45.375000   1.1   3.9  2.1  0.0   3.9   4.6   2.3  
137   83.00000  17.000000   0.0   4.7  0.0  0.0   2.6   2.6   0.0  
138   88.12500  13.980000   0.0  12.0  1.7  0.0   2.7   0.0   0.0  
139   98.66500  17.456000   1.7   7.0  1.2  0.0   4.8   3.1   0.0  

[140 rows x 18 columns]

In [20]:
df_t.isna().any()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17     True
dtype: bool

In [21]:
df_m=pd.DataFrame(df_t.iloc[:,15:18]).rename(columns={0:"15",1:"16",2:"17"})
p_m =pd.DataFrame(df_m.isnull().sum() * 100 / len(df_t)).rename(columns={0:"Percentage"})
p_m

Percentage
15    0.714286
16    0.714286
17    5.000000

The empty cells consist of very small proportions on this columns. We are going to fill them with the mean of the corresponding column.

In [22]:
df_m=df_m.fillna(df_m.mean())
df_m

15    16    17
0     1.2   0.0  28.0
1    23.2  46.4   0.0
2    21.2   0.0   2.1
3     4.8   1.0   1.2
4     0.0   0.0   0.0
..    ...   ...   ...
135   1.7   5.9   0.0
136   3.9   4.6   2.3
137   2.6   2.6   0.0
138   2.7   0.0   0.0
139   4.8   3.1   0.0

[140 rows x 3 columns]

Verify that the empty cells have been filled.

In [23]:
df_m.isna().any()

15    False
16    False
17    False
dtype: bool

In [24]:
df_t=df_t.iloc[:,0:15]
df_t=pd.concat([df_t,df_m],axis=1)
df_t

0       1       2     3     4        5      6          7          8   \
0    summer  small_  medium  7.95   5.7  57.3330  2.460  273.33301  295.66699   
1    winter  small_  medium  7.98   8.8  59.3330  7.392  286.66699   33.33300   
2    summer  small_  medium  8.00   7.2  80.0000  1.957  174.28600   47.85700   
3    spring  small_  high__  8.35   8.4  68.0000  3.026  458.00000   45.20000   
4    spring  small_  medium  8.10  13.2  19.0000  0.000  130.00000    6.00000   
..      ...     ...     ...   ...   ...      ...    ...        ...        ...   
135  summer  medium  high__  8.12  10.2   7.6130  0.699   33.56000   28.03400   
136  winter  large_  low___  8.43  10.8  35.6420  6.225  134.00000  103.50000   
137  winter  large_  low___  8.70  11.7  21.4656  3.765   91.45000   38.00000   
138  summer  large_  low___  8.10   8.2  26.5400  2.805   42.75000   48.50000   
139  autumn  large_  low___  8.35  11.1  22.5600  3.140   76.20000   41.00000   

            9          10    11    12   13   14    15    16    17  
0    380.00000  10.912868   1.2  36.5  1.9  0.0   1.2   0.0  28.0  
1    138.00000   7.100000   1.2   0.0  0.0  0.0  23.2  46.4   0.0  
2    113.71400   4.500000   7.0  23.0  6.5  1.4  21.2   0.0   2.1  
3    111.80000   3.200000   1.4  38.2  2.4  0.0   4.8   1.0   1.2  
4     40.00000   2.000000   3.9  55.4  8.4  0.0   0.0   0.0   0.0  
..         ...        ...   ...   ...  ...  ...   ...   ...   ...  
135   49.65800   2.200000  18.1   1.7  2.0  0.0   1.7   5.9   0.0  
136  108.80637  45.375000   1.1   3.9  2.1  0.0   3.9   4.6   2.3  
137   83.00000  17.000000   0.0   4.7  0.0  0.0   2.6   2.6   0.0  
138   88.12500  13.980000   0.0  12.0  1.7  0.0   2.7   0.0   0.0  
139   98.66500  17.456000   1.7   7.0  1.2  0.0   4.8   3.1   0.0  

[140 rows x 18 columns]

In [25]:
df_t_object=df_t.iloc[:,0:3]
df_t_object=df_t_object.apply(LabelEncoder().fit_transform)
df_t_object

0  1  2
0    2  2  2
1    3  2  2
2    2  2  2
3    1  2  0
4    1  2  2
..  .. .. ..
135  2  1  0
136  3  0  1
137  3  0  1
138  2  0  1
139  0  0  1

[140 rows x 3 columns]

In [26]:
df_s=df_t.iloc[:,3:18]
df_t=pd.concat([df_t_object,df_s],axis=1)
df_t

0   1   2     3     4        5      6          7          8          9   \
0     2   2   2  7.95   5.7  57.3330  2.460  273.33301  295.66699  380.00000   
1     3   2   2  7.98   8.8  59.3330  7.392  286.66699   33.33300  138.00000   
2     2   2   2  8.00   7.2  80.0000  1.957  174.28600   47.85700  113.71400   
3     1   2   0  8.35   8.4  68.0000  3.026  458.00000   45.20000  111.80000   
4     1   2   2  8.10  13.2  19.0000  0.000  130.00000    6.00000   40.00000   
..   ..  ..  ..   ...   ...      ...    ...        ...        ...        ...   
135   2   1   0  8.12  10.2   7.6130  0.699   33.56000   28.03400   49.65800   
136   3   0   1  8.43  10.8  35.6420  6.225  134.00000  103.50000  108.80637   
137   3   0   1  8.70  11.7  21.4656  3.765   91.45000   38.00000   83.00000   
138   2   0   1  8.10   8.2  26.5400  2.805   42.75000   48.50000   88.12500   
139   0   0   1  8.35  11.1  22.5600  3.140   76.20000   41.00000   98.66500   

            10    11    12   13   14    15    16    17  
0    10.912868   1.2  36.5  1.9  0.0   1.2   0.0  28.0  
1     7.100000   1.2   0.0  0.0  0.0  23.2  46.4   0.0  
2     4.500000   7.0  23.0  6.5  1.4  21.2   0.0   2.1  
3     3.200000   1.4  38.2  2.4  0.0   4.8   1.0   1.2  
4     2.000000   3.9  55.4  8.4  0.0   0.0   0.0   0.0  
..         ...   ...   ...  ...  ...   ...   ...   ...  
135   2.200000  18.1   1.7  2.0  0.0   1.7   5.9   0.0  
136  45.375000   1.1   3.9  2.1  0.0   3.9   4.6   2.3  
137  17.000000   0.0   4.7  0.0  0.0   2.6   2.6   0.0  
138  13.980000   0.0  12.0  1.7  0.0   2.7   0.0   0.0  
139  17.456000   1.7   7.0  1.2  0.0   4.8   3.1   0.0  

[140 rows x 18 columns]

In [27]:
df_t=pd.DataFrame(scaler.fit_transform(df_t))
df_t

0         1         2         3         4         5         6  \
0    0.538337  1.159999  1.111270 -0.048755 -1.598301  0.409818 -0.186692   
1    1.446376  1.159999  1.111270  0.006193 -0.187414  0.459788  1.903523   
2    0.538337  1.159999  1.111270  0.042825 -0.915614  0.976157 -0.399866   
3   -0.369701  1.159999 -1.095507  0.683886 -0.369464  0.676335  0.053183   
4   -0.369701  1.159999  1.111270  0.225985  1.815136 -0.547939 -1.229256   
..        ...       ...       ...       ...       ...       ...       ...   
135  0.538337 -0.108750 -1.095507  0.262617  0.449761 -0.832445 -0.933015   
136  1.446376 -1.377499  0.007881  0.830414  0.722836 -0.132136  1.408940   
137  1.446376 -1.377499  0.007881  1.324946  1.132448 -0.486335  0.366376   
138  0.538337 -1.377499  0.007881  0.225985 -0.460489 -0.359551 -0.040478   
139 -1.277740 -1.377499  0.007881  0.683886  0.859373 -0.458992  0.101497   

            7         8             9            10        11        12  \
0    0.512627  2.400913  2.775882e+00  2.087892e-10 -0.743580  2.903632   
1    0.582077 -0.357395  2.988200e-01 -2.932948e-01 -0.743580 -0.645599   
2   -0.003258 -0.204683  5.023348e-02 -4.932928e-01 -0.459926  1.590903   
3    1.474462 -0.232620  3.064218e-02 -5.932919e-01 -0.733799  3.068939   
4   -0.233921 -0.644788 -7.042878e-01 -6.855987e-01 -0.611534  4.741453   
..        ...       ...           ...           ...       ...       ...   
135 -0.736227 -0.413112 -6.054305e-01 -6.702142e-01  0.082931 -0.480292   
136 -0.213087  0.380375 -4.752334e-10  2.650908e+00 -0.748471 -0.266366   
137 -0.434708 -0.308324 -2.641487e-01  4.682364e-01 -0.802267 -0.188575   
138 -0.688361 -0.197922 -2.116902e-01  2.359310e-01 -0.802267  0.521272   
139 -0.514138 -0.276781 -1.038050e-01  5.033130e-01 -0.719127  0.035076   

           13        14        15        16        17  
0   -0.287667 -0.612966 -0.522395 -0.532720  5.846406  
1   -0.630804 -0.612966  1.772181  2.950837 -0.383961  
2    0.543084  0.025405  1.563583 -0.532720  0.083317  
3   -0.197368 -0.612966 -0.146919 -0.457644 -0.116945  
4    0.886221 -0.612966 -0.647553 -0.532720 -0.383961  
..        ...       ...       ...       ...       ...  
135 -0.269607 -0.612966 -0.470245 -0.089768 -0.383961  
136 -0.251547 -0.612966 -0.240788 -0.187368  0.127820  
137 -0.630804 -0.612966 -0.376376 -0.337521 -0.383961  
138 -0.323787 -0.612966 -0.365947 -0.532720 -0.383961  
139 -0.414086 -0.612966 -0.146919 -0.299983 -0.383961  

[140 rows x 18 columns]

In [28]:
X=df_t.iloc[:,features.index]
X.head()

0         1         2         3         4         5         6   \
0  0.538337  1.159999  1.111270 -0.048755 -1.598301  0.409818 -0.186692   
1  1.446376  1.159999  1.111270  0.006193 -0.187414  0.459788  1.903523   
2  0.538337  1.159999  1.111270  0.042825 -0.915614  0.976157 -0.399866   
3 -0.369701  1.159999 -1.095507  0.683886 -0.369464  0.676335  0.053183   
4 -0.369701  1.159999  1.111270  0.225985  1.815136 -0.547939 -1.229256   

         7         8         9             10  
0  0.512627  2.400913  2.775882  2.087892e-10  
1  0.582077 -0.357395  0.298820 -2.932948e-01  
2 -0.003258 -0.204683  0.050233 -4.932928e-01  
3  1.474462 -0.232620  0.030642 -5.932919e-01  
4 -0.233921 -0.644788 -0.704288 -6.855987e-01

In [29]:
y=df_t.iloc[:,11:18]
y

11        12        13        14        15        16        17
0   -0.743580  2.903632 -0.287667 -0.612966 -0.522395 -0.532720  5.846406
1   -0.743580 -0.645599 -0.630804 -0.612966  1.772181  2.950837 -0.383961
2   -0.459926  1.590903  0.543084  0.025405  1.563583 -0.532720  0.083317
3   -0.733799  3.068939 -0.197368 -0.612966 -0.146919 -0.457644 -0.116945
4   -0.611534  4.741453  0.886221 -0.612966 -0.647553 -0.532720 -0.383961
..        ...       ...       ...       ...       ...       ...       ...
135  0.082931 -0.480292 -0.269607 -0.612966 -0.470245 -0.089768 -0.383961
136 -0.748471 -0.266366 -0.251547 -0.612966 -0.240788 -0.187368  0.127820
137 -0.802267 -0.188575 -0.630804 -0.612966 -0.376376 -0.337521 -0.383961
138 -0.802267  0.521272 -0.323787 -0.612966 -0.365947 -0.532720 -0.383961
139 -0.719127  0.035076 -0.414086 -0.612966 -0.146919 -0.299983 -0.383961

[140 rows x 7 columns]

In [30]:
y_pred=best_random.predict(X)
y_pred=pd.DataFrame(y_pred)

In [31]:
n_classes=y.shape[1]
for i in range(n_classes):
    print("The root means square for the ",i,"th target is ,", np.sqrt(mse(y.iloc[:,i],y_pred.iloc[:,i]))  ) 

The root means square for the  0 th target is , 0.7037185552766403
The root means square for the  1 th target is , 0.9374496874516115
The root means square for the  2 th target is , 0.9368018881602461
The root means square for the  3 th target is , 0.9374330134312003
The root means square for the  4 th target is , 0.9058089844410483
The root means square for the  5 th target is , 0.8886978504231938
The root means square for the  6 th target is , 0.9790698527550512


In [33]:
for i in range(n_classes):
    print("The correlation for the ",i,"th target is: \n", np.corrcoef(y.iloc[:,i],y_pred.iloc[:,i]))

The correlation for the  0 th target is: 
 [[1.         0.71500377]
 [0.71500377 1.        ]]
The correlation for the  1 th target is: 
 [[1.         0.35205131]
 [0.35205131 1.        ]]
The correlation for the  2 th target is: 
 [[1.         0.36428047]
 [0.36428047 1.        ]]
The correlation for the  3 th target is: 
 [[1.         0.36676466]
 [0.36676466 1.        ]]
The correlation for the  4 th target is: 
 [[1.         0.45251129]
 [0.45251129 1.        ]]
The correlation for the  5 th target is: 
 [[1.         0.47116157]
 [0.47116157 1.        ]]
The correlation for the  6 th target is: 
 [[1.        0.2135969]
 [0.2135969 1.       ]]


**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.**.